version: '3.8'

services:
  joomla:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: root
      JOOMLA_DB_NAME: joomla
    depends_on:
      - db

db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
    ports:
      - "3306:3306"
    volumes:
      - ./tests/sql:/docker-entrypoint-initdb.d
volumes:
  db_data:
