services:
  joomla:
    image: ghcr.io/trevorbicewebdesign/mothership:php8.2-joomla5.3.0
    pull_policy: if_not_present
    ports:
      - "8080:80"
    depends_on:
      - db
      - selenium
    volumes:
      - ./tests:/var/www/html/tests
      - ./site:/var/www/html/components/com_mothership
      - ./admin:/var/www/html/administrator/components/com_mothership
      - ./mothership.xml:/var/www/html/administrator/components/com_mothership/mothership.xml
      
      - ./admin/language/en-GB/com_mothership.ini:/var/www/html/administrator/language/en-GB/com_mothership.ini
      - ./admin/language/en-GB/com_mothership.sys.ini:/var/www/html/administrator/language/en-GB/com_mothership.sys.ini
      - ./site/language/en-GB/com_mothership.ini:/var/www/html/language/en-GB/com_mothership.ini
      - ./site/language/en-GB/com_mothership.sys.ini:/var/www/html/language/en-GB/com_mothership.sys.ini

      - ./plugins/mothership-payment/paybycheck/language/en-GB/en-GB.plg_mothership-payment_paybycheck.ini:/var/www/html/administrator/language/en-GB/plg_mothership-payment_paybycheck.ini
      - ./plugins/mothership-payment/paybycheck/language/en-GB/en-GB.plg_mothership-payment_paybycheck.sys.ini:/var/www/html/administrator/language/en-GB/plg_mothership-payment_paybycheck.sys.ini
      - ./plugins/mothership-payment/zelle/language/en-GB/en-GB.plg_mothership-payment_zelle.ini:/var/www/html/administrator/language/en-GB/plg_mothership-payment_zelle.ini
      - ./plugins/mothership-payment/zelle/language/en-GB/en-GB.plg_mothership-payment_zelle.sys.ini:/var/www/html/administrator/language/en-GB/plg_mothership-payment_zelle.sys.ini

      - ./plugins/mothership-payment:/var/www/html/plugins/mothership-payment
      - ./codeception.yml:/var/www/html/codeception.yml
      - ./tests/configuration.php:/var/www/html/configuration.php
    restart: always

  db:
    image: ghcr.io/trevorbicewebdesign/mysql:8.0
    pull_policy: if_not_present
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
    ports:
      - "3306:3306"
    volumes:
      - ./tests/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  selenium:
    image: ghcr.io/selenium/standalone-chrome:129.0
    pull_policy: if_not_present
    ports:
      - "4444:4444"
    shm_size: 2gb
  
  mailpit:
    image: ghcr.io/trevorbicewebdesign/mailpit:1.18.0
    pull_policy: if_not_present
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP port
    restart: always

volumes:
  db_data:
