services:
  joomla:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./tests:/var/www/html/tests
      - ./site:/var/www/html/components/com_mothership
      - ./admin:/var/www/html/administrator/components/com_mothership
      - ./mothership.xml:/var/www/html/administrator/components/com_mothership/mothership.xml
      - ./admin/language/en-GB/com_mothership.ini:/var/www/html/administrator/language/en-GB/com_mothership.ini
      - ./admin/language/en-GB/com_mothership.ini:/var/www/html/administrator/language/en-GB/com_mothership.sys.ini
      - ./site/language/en-GB/com_mothership.ini:/var/www/html/language/en-GB/com_mothership.ini
      - ./site/language/en-GB/com_mothership.ini:/var/www/html/language/en-GB/com_mothership.sys.ini
      - ./plugins/mothership-payment:/var/www/html/plugins/mothership-payment
      - ./codeception.yml:/var/www/html/codeception.yml
      - ./tests/composer.json:/var/www/html/composer.json
      - ./tests/composer.lock:/var/www/html/composer.lock

    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
    ports:
      - "3306:3306"
    volumes:
      - ./tests/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
