version: '3.8'

services:
  joomla:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/tmp/mothership
      - ./tests:/var/www/html/tests

    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
    ports:
      - "3306:3306"
    volumes:
      - ./tests/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
